const Q=[
/* ---------------- BOARD 1 — THE CARE HOME (MCA + deprivation of liberty) ---------------- */
{lv:1,q:'Edith wants to spend her savings on a cruise. Her family think it a terrible idea. Does that mean she lacks capacity to decide?',
 a:['No — an unwise decision does not, by itself, establish incapacity','Yes — it is plainly against her interests','Only if the family object formally'],
 w:'A person is not to be <i>treated as</i> unable to make a decision merely because it is unwise. An unwise decision may fairly prompt an assessment, and may be evidence going to whether she can use or weigh the information — but on its own it establishes nothing.',
 c:'s.1(4) MCA 2005; Kings College Hospital NHS FT v C [2015] EWCOP 80; PC v City of York Council [2013] EWCA Civ 478'},
{lv:1,q:'Where do you start when a question about Edith’s capacity arises?',
 a:['Assume she has capacity unless it is established that she lacks it','Assess her capacity before assuming anything','Ask the family what they think'],
 w:'The presumption of capacity is the starting point every time, and the burden falls on whoever asserts incapacity. In proceedings the question is decided on the balance of probabilities; whether that same standard governs a care home’s own out-of-court assessment is contested.',
 c:'s.1(2) MCA 2005; s.2(4) (in proceedings)'},
{lv:1,q:'Before concluding that Edith is unable to make a decision, what must have happened?',
 a:['All practicable steps to help her decide must have been tried, without success','A doctor must have signed a form','She must have been asked twice'],
 w:'A different time of day, simpler language, an interpreter, a photograph, a familiar person in the room. The duty is to support the decision before displacing it.',
 c:'s.1(3) MCA 2005'},
{lv:1,q:'Is capacity global — either you have it or you do not?',
 a:['No — it is specific to the decision and to the time','Yes, a dementia diagnosis settles it','Yes, once an assessment is on file'],
 w:'Capacity is assessed in relation to a particular matter at the material time, so Edith may lack it about her care arrangements and keep it about who visits her. Start by defining the matter, then the relevant information, then s.3 — never with the diagnosis.',
 c:'ss.2(1), 2(3) MCA 2005; A Local Authority v JB [2021] UKSC 52'},
{lv:1,q:'Edith’s daughter is her next of kin. Can she consent to Edith’s care arrangements on Edith’s behalf?',
 a:['No — "next of kin" has no meaning in the Act and carries no decision-making power','Yes, as the closest relative','Yes, if she signs the care plan'],
 w:'Only a health and welfare attorney under a registered LPA, a court-appointed deputy, or the court itself can decide for Edith; otherwise the act is the carer’s own under s.5 and the daughter must be consulted, not obeyed. Do not confuse this with the <i>nearest relative</i> under the Mental Health Act, who does have statutory powers.',
 c:'ss.4(7), 5, 6(6), 9–14, 16 MCA 2005; cf. s.26 MHA 1983'},
{lv:1,q:'What is the current test for whether arrangements amount to a deprivation of liberty?',
 a:['The multi-factorial Guzzardi approach — the whole concrete situation, no single factor decisive','The acid test: continuous supervision and control, and not free to leave','The acid test, unless the placement is relatively normal'],
 w:'The Cheshire West "acid test" was set aside by the Supreme Court in the AGNI reference, with immediate effect from 2 June 2026 and no grace period. You now weigh the type, duration, effects and manner of implementation of the restrictions, asking how close they come to the paradigm case — detention in a prison cell.',
 c:'AGNI [2026] UKSC 16 at [119]; Guzzardi v Italy (1981) 3 EHRR 333'},
{lv:1,q:'The front door is locked so residents cannot wander into the road, and staff know where Edith is through the day. Is that, without more, a deprivation of her liberty?',
 a:['No — restrictions that are fairly limited are unlikely on their own to meet the objective element','Yes — she is supervised and not free to leave, so the test is met','Yes — any locked door in a care home is a deprivation of liberty'],
 w:'Locking a care home door to stop residents who cannot look after themselves wandering into the street is the Supreme Court’s own example of a restriction unlikely by itself to satisfy the objective element. If the person does not experience it as a major intrusion, that points to a restriction on liberty of movement rather than a deprivation of liberty.',
 c:'AGNI [2026] UKSC 16 at [136(iv)]'},
{lv:1,q:'Two people have the same package — 24-hour supervision, a locked door, escorted trips out. One is in a care home, the other in her own flat, where she has always wanted to be, with a live-in carer. Does the setting matter?',
 a:['Yes — relative normality is a relevant factor, and living in your own home in accordance with your wishes makes a deprivation less likely','No — the comparator is a person of the same age without disabilities','No — a gilded cage is still a cage'],
 w:'Relative normality is now a relevant factor in the objective element, running along a spectrum from the most normal arrangements to settings designed for compulsory detention. Where someone lives in their own home in accordance with their wishes, the restrictions would need to be more severe — restraint, medication and seclusion in combination, for example — although even a domestic setting can involve a deprivation of liberty.',
 c:'AGNI [2026] UKSC 16 at [53(iv)], [54], [193]'},
{lv:1,q:'Edith lacks capacity to decide where she lives. She settled quickly, seeks out staff, and shows every sign of contentment. Is that legally relevant?',
 a:['Yes — a tacit positive indication of contentment may amount to valid consent, even though she lacks capacity','No — someone who lacks capacity cannot consent, so only an authorisation makes it lawful','No — compliance and absence of objection are irrelevant'],
 w:'Consent for Article 5 purposes is an autonomous concept, untethered to the domestic test of decision-making capacity, so a person who lacks capacity to decide on residence and care can still give or withhold valid consent through their wishes and feelings. Be practical and realistic: draw no inference of consent where there is serious doubt, and give compliance less weight where sedative medication may be suppressing objection.',
 c:'AGNI [2026] UKSC 16 at [53(ii)], [172], [188], [191], [201]'},
{lv:1,q:'Mr Hallam has advanced dementia and is in hospital with pneumonia. He is confused, and staff would stop him leaving the ward while he is unwell. Does the reason for the restrictions matter?',
 a:['Yes — purpose is relevant once the situation is far from the paradigm of a prison cell, though not decisive','No — a benign motive cannot stop something being a deprivation of liberty','Yes — a therapeutic purpose is a complete answer'],
 w:'Purpose was expressly irrelevant under Cheshire West and is now a relevant but non-decisive factor. In ordinary circumstances a patient in hospital for treatment who would be stopped from leaving for their own protection while confused would not be regarded as deprived of liberty, absent evidence of detention in fact or a clear pattern of objection.',
 c:'AGNI [2026] UKSC 16 at [53(iv)], [129]–[130], [145]'},
{lv:1,q:'You conclude that Edith, in her own flat with a live-in carer, IS deprived of her liberty. Can DoLS authorise it?',
 a:['No — DoLS reaches hospitals and care homes only, so you need a Court of Protection order','Yes — DoLS covers any setting the council funds','Yes, once the care plan is signed off'],
 w:'Schedule A1 reaches only hospitals and care homes; supported living and a person’s own home fall outside it, and the route is a welfare order under s.16(2)(a) authorising the deprivation. AGNI changed who is deprived of liberty, not the authorisation machinery — DoLS remains in force and LPS has never been commenced.',
 c:'ss.4A(3), 16(2)(a), Sch A1 MCA 2005'},
{lv:1,q:'Chloe is 17 and in a care home under arrangements you have decided do deprive her of liberty. Is DoLS available?',
 a:['No — DoLS is for those aged 18 and over; at 16 or 17 you need the Court of Protection','Yes, with parental consent','Yes — DoLS has no age limit'],
 w:'Age is one of the six DoLS assessments. The Court of Protection’s jurisdiction begins at 16, so a welfare order is the route; below 16 you are looking at the Children Act or the inherent jurisdiction. Parents cannot consent to arrangements amounting to a deprivation of liberty for a 16 or 17 year old.',
 c:'ss.2(5), 16(2)(a) and Sch A1 MCA 2005; Re D (A Child) [2019] UKSC 42'},
{lv:1,q:'How long may a standard authorisation last, and how long an urgent one?',
 a:['Standard: up to 12 months. Urgent: 7 days, extendable in exceptional circumstances by up to 7 more','Both 28 days','Standard 6 months, urgent 14 days'],
 w:'Twelve months is a maximum, not a default — the authorisation must run for the shortest period appropriate in the circumstances. The supervisory body can extend an urgent authorisation only in exceptional circumstances, and only by up to a further seven days: fourteen in total.',
 c:'Sch A1 MCA 2005'},
{lv:1,q:'In a best interests decision, can Edith’s behaviour be taken into account?',
 a:['Yes — but the decision must not be made merely on the basis of behaviour prompting unjustified assumptions','No — s.4(1) forbids any regard to age, appearance, condition or behaviour','Only where a clinician has recorded it'],
 w:'Section 4(1) bars a decision made <i>merely</i> on the basis of age, appearance, condition or behaviour where that would lead to unjustified assumptions. Behaviour remains central evidence of Edith’s past and present wishes and feelings, which the decision-maker must consider so far as they are reasonably ascertainable.',
 c:'ss.4(1), 4(6) MCA 2005'},
/* ---------------- BOARD 2 — THE WARD (Mental Health Act) ---------------- */
{lv:2,q:'How long may detention under s.2 and s.3 MHA 1983 last?',
 a:['s.2: 28 days, not renewable. s.3: 6 months, renewable','Both 28 days','s.2: 72 hours. s.3: 28 days'],
 w:'Section 2 is for assessment and simply expires at 28 days. Section 3 is for treatment: six months, then a further six, then annually. The Mental Health Act 2025 will cut the initial s.3 period to three months, but it is not yet in force.',
 c:'ss.2, 3, 20 MHA 1983'},
{lv:2,q:'How long do the holding powers in s.5(2) and s.5(4) last, and who may use them?',
 a:['s.5(2) the doctor or approved clinician in charge, 72 hours; s.5(4) a nurse of the prescribed class, 6 hours','Any doctor on the ward, 72 hours; any nurse, 6 hours','Both last 72 hours'],
 w:'Section 5(2) belongs to the registered medical practitioner or approved clinician in charge of the patient’s treatment, or one nominated deputy — not to any doctor on the ward. The nurse’s power runs for up to six hours, or until a doctor with s.5(2) power arrives, whichever is sooner. Neither is authority to treat.',
 c:'s.5 MHA 1983'},
{lv:2,q:'What does s.4 MHA 1983 permit, and what happens when a second medical recommendation arrives?',
 a:['Emergency admission for up to 72 hours on one recommendation; a second converts it to s.2, and the 28 days runs from the original admission','Admission for treatment for 28 days; a second recommendation extends it','Police removal from a public place for 72 hours'],
 w:'Section 4 is for genuine urgent necessity, where waiting for a second recommendation would cause undesirable delay — not administrative convenience. The trap is the clock: once converted, the 28 days runs from the original s.4 admission, not from the date of the second recommendation.',
 c:'ss.4, 4(4) MHA 1983'},
{lv:2,q:'What is the maximum period of detention under s.136, and when does it start?',
 a:['24 hours from arrival at the place of safety, extendable by up to 12 more','72 hours from the moment of detention','36 hours from arrival, not extendable'],
 w:'The Policing and Crime Act 2017 cut the period from 72 hours to 24, and the clock starts on arrival at the place of safety rather than at the moment of detention. A police station may be used as a place of safety for an adult only in specified exceptional circumstances, and never for a child.',
 c:'ss.136, 136A, 136B MHA 1983, as amended'},
{lv:2,q:'Who may apply for admission under s.3, and what medical evidence is needed?',
 a:['An AMHP or the nearest relative, with two recommendations, at least one from a s.12 approved doctor','Any doctor alone','The care coordinator with one recommendation'],
 w:'In practice the AMHP applies. At least one of the two recommendations must come from a s.12 approved practitioner, and if practicable one should come from a doctor with previous acquaintance with the patient. Watch the conflict-of-interest bar as well.',
 c:'ss.3, 11, 12, 12A MHA 1983'},
{lv:2,q:'Can the nearest relative prevent an application for admission being made?',
 a:['Yes for s.3 and guardianship, by objecting; for s.2 the AMHP need only take practicable steps to inform them','Yes, for any detention','No — the nearest relative has no such power'],
 w:'An AMHP cannot make a s.3 application if the nearest relative objects, and the route round an unreasonable objection is displacement under s.29. Keep that separate from the nearest relative’s quite different power to order discharge, which the responsible clinician can defeat with a barring certificate.',
 c:'ss.11(3), 11(4), 23, 25, 29 MHA 1983'},
{lv:2,q:'P is married but permanently separated in fact from her husband, with no agreement or order. Her adult son has cared for her daily in her own home for two years. Who is the nearest relative?',
 a:['The son — a relative who resides with or cares for the patient takes precedence over everyone else','The husband — a spouse always ranks first unless separated by agreement or court order','Neither — they rank equally, so the elder prevails'],
 w:'Section 26(4) requires the nearest relative to be determined as if only those relatives residing with or caring for the patient were on the list, and there is no carve-out for a spouse. This is the single most common error in nearest relative identification, and the natural trap for any flowchart that checks for a spouse first.',
 c:'ss.26(1), 26(4) MHA 1983'},
{lv:2,q:'Which patients become entitled to s.117 aftercare, and who pays?',
 a:['Those who cease to be detained under ss.3, 37, 45A, 47 or 48 — and it must be provided free of charge','Anyone discharged from hospital, subject to a means test','Only s.3 patients, subject to a means test'],
 w:'Section 117 is a free-standing duty on the integrated care board and the local authority, and charging for a service that meets a s.117 need is unlawful. The duty attaches on ceasing to be detained, not during the detention itself; top-up payments for preferred accommodation are the one qualification.',
 c:'ss.117, 117A MHA 1983; R (Stennett) v Manchester CC [2002] UKHL 34'},
{lv:2,q:'P has been receiving s.117 aftercare from Authority A. He is re-detained under s.3. What happens to the duty?',
 a:['It ends — s.117 cannot run alongside a live s.3 — and a fresh duty arises on the next discharge','It continues unbroken with Authority A until A and the ICB jointly decide aftercare is no longer needed','It transfers automatically to the authority where he is now placed'],
 w:'The Supreme Court held that s.117 does not apply to a person currently detained under s.3, but only to a person who has ceased to be so detained, so re-detention brings the existing duty to an end. A voluntary admission or a s.2 admission does not have that effect. The Mental Health Act 2025 will change the ordinary residence outcome, but is not yet in force.',
 c:'s.117 MHA 1983; R (Worcestershire CC) v SSHSC [2023] UKSC 31 at [45], [53]'},
{lv:2,q:'A patient detained under s.2 wants to challenge it. What is the time limit for a tribunal application?',
 a:['Within 14 days beginning with the day of admission','Within 28 days','At any time during the 28 days'],
 w:'The window is short and the hearing must be listed quickly. Miss it and what remains is the hospital managers’ power of discharge, and the application window that opens if the patient moves onto s.3.',
 c:'s.66 MHA 1983'},
{lv:2,q:'Which patients may be placed on a community treatment order?',
 a:['Patients detained under s.3, or unrestricted Part 3 patients','Any detained patient, including s.2','Any patient with a care plan'],
 w:'A CTO runs for an initial six months and requires the responsible clinician and an AMHP to agree. Restricted patients are excluded — conditional discharge is their route. MM held that neither the tribunal nor the Secretary of State could impose conditions amounting to a deprivation of liberty, but the Mental Health Act 2025 reversed that: since 18 February 2026 amended ss.42 and 73 permit such conditions where necessary to protect others from serious harm (and, for the tribunal, where discharge would be no less beneficial to the patient). Note that both the First-tier Tribunal and HMPPS guidance treat the conditions as unenforceable against an unwilling patient, and AGNI has unsettled the Article 5 premise on which MM rested.',
 c:'s.17A MHA 1983; ss.42, 73 MHA 1983 as amended by the Mental Health Act 2025 (in force 18 February 2026); SSJ v MM [2018] UKSC 60; Welsh Ministers v PJ [2018] UKSC 66; cf. AGNI [2026] UKSC 16 at [53(ii)], [172]'},
{lv:2,q:'The Mental Health Act 2025 received Royal Assent in December 2025. Which Act should you apply on the ward today?',
 a:['The 1983 Act as amended — only two narrow 2025 Act provisions have commenced','The 2025 Act, since Royal Assent brings an Act into force','Whichever is more favourable to the patient'],
 w:'Royal Assent is not commencement. Two provisions are already in force from 18 February 2026 — the widened s.48 transfer power and conditional discharge with deprivation-of-liberty conditions for restricted patients. The rest — the serious harm threshold, the three-month initial s.3 period, the nominated person replacing the nearest relative, advance choice documents, the removal of police stations as places of safety — awaits a new Code of Practice and its own commencement regulations, and is not expected before 2027–2028.',
 c:'Mental Health Act 2025 (c.33), Royal Assent 18 December 2025'},
/* ---------------- BOARD 3 — THE COURT (Court of Protection) ---------------- */
{lv:3,q:'Which section allows P to challenge a standard or urgent authorisation, and what does it cover?',
 a:['s.21A — but it reaches the deprivation of liberty itself, not the welfare decisions leading up to it','s.21A — and it carries any welfare or treatment issue with it','s.16 — a fresh welfare application must be issued'],
 w:'Section 21A is the dedicated route and carries non-means-tested legal aid for P, which is why identifying it correctly matters. Its scope is narrow: it relates to decisions about the deprivation of liberty and not to the circumstances leading up to it, so serious medical treatment must go under ss.15–17.',
 c:'s.21A MCA 2005; Director of Legal Aid Casework v Briggs [2017] EWCA Civ 1169 at [89]'},
{lv:3,q:'The court can either make the decision itself or appoint a deputy. Which does the Act prefer?',
 a:['A decision of the court, in preference to appointing a deputy','A deputy, to avoid repeated hearings','Neither is preferred'],
 w:'Section 16(4) states the preference expressly. Where a deputy is appointed, the powers conferred must be as limited in scope and duration as is reasonably practicable.',
 c:'s.16(4) MCA 2005'},
{lv:3,q:'What must the court be satisfied of before making an interim order under s.48?',
 a:['Reason to believe P lacks capacity, that the matter is within its powers, and that it is in P’s best interests to act without delay','That P lacks capacity on the balance of probabilities, and that the matter is urgent','That all parties consent and the matter is urgent'],
 w:'The three limbs are reason to believe, jurisdiction, and best interests without delay — urgency is not a freestanding condition, it sits inside the third limb. Whether "reason to believe" lowers the standard of proof, or simply asks a different and preliminary question, remains unresolved at appellate level.',
 c:'s.48 MCA 2005; cf. Somerset NHS Foundation Trust v Amira [2023] EWCOP 25 at [54]; DP v LB Hillingdon [2020] EWCOP 45 at [40]'},
{lv:3,q:'What does s.49 allow the court to do?',
 a:['Require a report from an NHS body, a local authority, the Public Guardian or a Court of Protection Visitor','Require a report from any independent expert the court chooses','Compel a treating clinician to attend and give oral evidence'],
 w:'Section 49 is directed at bodies and office-holders, and a body may in turn arrange the report from someone it considers appropriate, who need not be its employee. What the court cannot do is name an independent expert of its own choosing — that needs permission under Part 15. Judges have warned that s.49 requests risk becoming disproportionate and overly burdensome.',
 c:'s.49 MCA 2005; PD 14E; Cheshire & Wirral Partnership NHS FT v JMC [2023] EWCOP 14'},
{lv:3,q:'May a deputy refuse consent to life-sustaining treatment on P’s behalf?',
 a:['No — a deputy has no such power','Yes, if the order says so','Yes, if the family agree'],
 w:'A health and welfare attorney can, but only where the lasting power of attorney expressly authorises it. A deputy never can. The court decides.',
 c:'ss.11(8), 20(5) MCA 2005'},
{lv:3,q:'What formalities must an advance decision refusing life-sustaining treatment satisfy?',
 a:['In writing, signed, witnessed, and verified by a statement that it applies even if life is at risk','Signed by a doctor','None — an oral refusal is enough'],
 w:'Advance decisions about other treatment need no formality at all. It is only the life-sustaining category that carries these requirements, and the "even if life is at risk" statement is the one most often missing.',
 c:'ss.25(5), 25(6) MCA 2005'},
{lv:3,q:'A deprivation of liberty needs authorising and an application to the court is being made. What permits it in the meantime?',
 a:['s.4B, for life-sustaining treatment or a vital act while a decision from the court is sought','s.5, for as long as it takes','Nothing — the arrangements must stop'],
 w:'Section 4A provides that a deprivation of liberty needs court authorisation or DoLS; s.4B is the narrow interim gateway. Note that the substituted s.4B in the Mental Capacity (Amendment) Act 2019 is not in force — LPS was never commenced — so the provision that applies is the original one, which requires an application actually to have been made, not merely contemplated.',
 c:'ss.4A, 4B MCA 2005 as originally enacted; MC(A)A 2019 not commenced'},
{lv:3,q:'Edith’s family privately fund and arrange her live-in care at home. The council knows all about it. Can Article 5 reach those arrangements?',
 a:['Yes — a deprivation must be imputable to the State, and that is readily established where public officials are on notice','No — Article 5 binds public authorities, and this is a private family arrangement','Only if the council is paying for some part of the package'],
 w:'A deprivation of liberty has three elements and all three must be present: the objective element, the absence of valid consent, and attribution to the State. In the care context attribution is relatively easy to establish, in particular where public officials know or ought to know of the arrangements and take no step to investigate.',
 c:'Storck v Germany (2005) 43 EHRR 6; AGNI [2026] UKSC 16 at [13] and fn 3; A Local Authority v A (A Child) [2010] EWHC 978 (Fam) at [95]–[96]'},
{lv:3,q:'A 2024 welfare order authorises P’s confinement in supported living. It was made on the acid test. P is settled and consistently content. On the annual review, what must the court decide first?',
 a:['Whether P is deprived of liberty at all on the Guzzardi approach, including whether her contentment is valid consent','Whether the arrangements remain in her best interests — the deprivation question was settled when the order was made','Whether to convert the order into a standard authorisation'],
 w:'AGNI set aside Cheshire West with immediate effect and no grace period, so an order premised on the acid test can no longer be assumed to be authorising anything. If the multi-factorial analysis and P’s consent take the arrangements outside Article 5, no authorisation is needed and the order should be discharged rather than renewed.',
 c:'AGNI [2026] UKSC 16 at [53], [191], [201]; ss.4A(3), 16(2)(a) MCA 2005'},
{lv:3,q:'A journalist observing a hearing listed in public asks for the parties’ position statements. What is the correct approach?',
 a:['Do not hand them over — court authorisation is needed; offer a case summary, chronology or list of issues instead','Provide them, since a public hearing makes the documents public','Provide them redacted — position statements are not court records'],
 w:'Court of Protection proceedings are private by default even where a hearing is directed to be held in public. Position statements are court records once lodged, but disclosure to a non-party requires authorisation, and the court must actively consider refusing, redacting or restricting use.',
 c:'Re Gardner (Deceased) [2026] EWCA Civ 640; COPR 2017 rr.4.1, 4.3, 5.9'},
{lv:3,q:'An expert reports that P "lacks insight into her mental illness" and therefore lacks capacity to decide where to live. What is the principal legal error?',
 a:['Treating P’s own mental impairment as information she must understand, use and weigh — deciding the first stage by the impairment instead of resolving the functional dispute','No error — a lack of insight is itself an inability to use or weigh','The error is one of standard of proof'],
 w:'Importing insight into the s.3 assessment conflates the two stages of the test and produces circular reasoning, in which the impairment proves the inability it is supposed to explain. Take the functional question first and the causative nexus second — and note that the Code of Practice directs people the wrong way round. Insight is not in a separate silo: whether a person’s grasp of the impact of their condition is relevant information depends on the decision in question.',
 c:'ss.2(1), 3(1) MCA 2005; CT v LB Lambeth [2025] EWCOP 6; A Local Authority v JB [2021] UKSC 52; B v A Local Authority [2019] EWCA Civ 913'},
{lv:3,q:'What is the status of the Liberty Protection Safeguards in July 2026?',
 a:['Enacted in 2019 but never commenced — DoLS remains the scheme in force','In force since April 2023, replacing DoLS','Commenced in June 2026 in response to AGNI'],
 w:'LPS was enacted by the Mental Capacity (Amendment) Act 2019, paused indefinitely in April 2023, and has no announced commencement date. AGNI changed who is deprived of liberty, not the machinery that authorises it.',
 c:'Mental Capacity (Amendment) Act 2019, not commenced'},
];
